name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # THIS IS THE NEW PART - It sets up and runs Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build

      # The upload part remains the same, but it will find the JAR in a different folder
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MythicMerchants-Plugin
          path: build/libs/*.jar # Gradle puts the final JAR in build/libs
