name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # This step installs the Gradle program onto the virtual machine
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # This step now uses the installed 'gradle' command directly
      # It does NOT use './gradlew'
      - name: Build with Gradle
        run: gradle build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MythicMerchants-Plugin
          # The path to find the final .jar file
          path: build/libs/*.jar
          
