name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated from v3 to v4

      # Step 2: Sets up the Java version needed for Minecraft plugins (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Updated from v3 to v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Runs the Maven build command to compile the project
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Step 4: Uploads the compiled .jar file so you can download it
      - name: Upload artifact
        uses: actions/upload-artifact@v4 # THIS IS THE KEY CHANGE - Updated from v3 to v4
        with:
          name: MythicMerchants-Plugin
          # The path to the file(s) to upload. The wildcard * means it will grab the jar regardless of version number.
          path: target/*.jar
